name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install isort
          pip install black

      - name: Lint with flake8
        run: flake8 --max-line-length=120 .

      - name: Lint with black
        run: black --check .

      - name: Lint with isort
        run: isort --check .